### ISSUE TITLE
[Plugin request] Svelte

### ISSUE THREAD

**Issue by Lumca** [rxi/lite-plugins#123]
Hello,

I have tried to make my own syntax but always failed, with syntaxing something from CSS in JS code or HTML code in JS code.

I would need to differ the syntax in <script> JS code </script>, <style> CSS code </style>code and in any other area of the code to have HTML syntax.

Or can it be done only with the syntax function that exists?

thanks
Lumir

**Comment by Darival** [comment]
If there is a way to do this i'd like to know/help, right now im using the language_js.lua for this.

**Comment by AqilCont** [comment]
Something deviating from the color_preview plugin would work, where it tracks the context and applies the correct highlighting for those files line by line whenever necessary. It would probably be better to completely remove the language plugin files too if this is implemented.
