### ISSUE TITLE
theme plugin

### ISSUE THREAD

**Issue by monolifed** [rxi/lite-plugins#14]
https://github.com/monolifed/theme16
(I decided not to do a PR because of the number of files and their different licenses)

**Comment by rxi** [comment]
This is very, *very* cool! For larger plugins it probably makes sense to link directly to other repos; I'll update the readme to reflect this and add a link to your repo for this plugin -- let me know if this isn't ok!

Thanks for making the plugin and the issue!

**Comment by monolifed** [comment]
Thanks for adding it.
