### ISSUE TITLE
 [Plugin Request] Count find occurences

### ISSUE THREAD

**Issue by Narann** [rxi/lite-plugins#162]
Hello and thanks for your hard work. :)

I would love to have a command to count the number of occurrence matching current find string.

Notepad++ have a similar function.

A big thanks to the one wanted to do this. :)

Have a nice day.

**Comment by SwissalpS** [comment]
you can search and replace, replacing with the same string as you search for.

**Comment by Narann** [comment]
Thanks. I should have been more clear.

By _count_ I mean: Get the number of occurrence of a particular string. :)

**Comment by SwissalpS** [comment]
Yes, after 'replacing' the count is shown in the status bar.

(Just a suggestion until somebody bothers to add another way to do so)

**Comment by Narann** [comment]
It’s definitely not easy, because you need to select the whole text (or unselect everything).

If you do a selection, then Ctrl+R then enter twice, il will replace only one occurrence, as it work on selection by default.

A cool feature would be a simple Ctrl+F, and a Ctrl+O, and having a « X occurence found ». It would be straightforward to the Ctrl+F feature, IMHO.

**Comment by SwissalpS** [comment]
Maybe Ctrl+Shift+F as we wouldn't want Ctrl+F to always search the entire document.

**Comment by Narann** [comment]
Ctrl+F enter a mode where you can switch find type (Ctrl+shift+i toogle regex mode). I simply propose to have an additional mode triggered by Ctrl+o (or Ctrl+shift+o) that count the number of occurrence.

**Comment by SwissalpS** [comment]
As far as I can tell, rxi/lite doesn't support Ctrl+shift+I (regex mode). Maybe you are using liteXL?

**Comment by Narann** [comment]
> Maybe you are using liteXL?

Yes, I’m dumb, I was sure I posted of the lite-YL plugin repo… I’m sorry for making you loose your precious time.

**Comment by SwissalpS** [comment]
No time lost, just repost on the liteXL-plugins repository ;)
