### ISSUE TITLE
Request: code folding

### ISSUE THREAD

**Issue by 636f6d6d656e740a** [rxi/lite-plugins#30]
A code folding plugin would be really helpful. Ideally it could automatically detect fold points at `{}` and indentation, and could allow you to define fold points like so 
```
-- Something {{{
code here!
-- }}}

-- folded up looks like:
+-- 1 line: Something
```
This is how Vim handles it, other syntax or behavior would be fine too. Ive been trying to write this myself but I don't know enough Lua or enough about the lite api to make it work.

**Comment by rxi** [comment]
Given lite's goal of simplicity, anything concerning virtual-lines or variable-line-heights is outside the scope of the project at the moment -- that unfortunately includes both code folding and soft word-wrapping. Both these things would require a rewrite of the `DocView` itself which would be non-trivial.

**Comment by 636f6d6d656e740a** [comment]
Ah ok, thanks for letting me know. If it becomes possible in the future that would be great.
