### ISSUE TITLE
Copying filelocation

### ISSUE THREAD

**Issue by harikt** [rxi/lite-plugins#31]
Sometimes I need to copy the file location and share to someone in the team.

So I wrote a small plugin looking at some of the lua files. I am learning lua via lite. So thought of sharing it as gist for this currently doesn't have copy clipboard in Windows.

```lua
-- data/plugins/copyfilelocation.lua
local core = require "core"
local command = require "core.command"
local config = require "core.config"


command.add("core.docview", {
  ["copy-file-location:copy-file-location"] = function()
    local doc = core.active_view.doc
    if not doc.filename then
      core.error "Cannot copy location of unsaved doc"
      return
    end
    local filename = doc.filename
    core.log("Copying \"%s\"", filename:gsub(".lua$", ""))
    if PLATFORM == "Windows" then
--       os.execute(string.format("start %s %s", config.filemanager, folder_name))
    else
      os.execute(string.format("echo %s | xclip -selection clipboard", filename:gsub(".lua$", "")))
    end
  end
})
```

If this can be improved or need a PR I am happy to send it.

Thank you.

**Comment by rxi** [comment]
lite provides `system.set_clipboard(text)` for copying text to the clipboard. That being said the functionality of this plugin could also be achieved by pressing: `ctrl+shift+s`, `ctrl+a`, `ctrl+c`

**Comment by harikt** [comment]
Interesting... and thank you for the tip. But this doesn't give you full path.

I also noticed some other problem with my plugin itself. What I tried to achieve with `filename:gsub(".lua$", ""))` was to get realpath :-) . But it looks like it was removing the `.lua` . My bad I want to learn some lua now.
