### ISSUE TITLE
Question : Workspace plugin

### ISSUE THREAD

**Issue by harikt** [rxi/lite-plugins#33]
Hi,

I recently used the workspace plugin. I currently created the file  `.lite_workspace.lua` manually to make it work. Didn't noticed any command to save the workspace.

Isn't that helpful to have a command to save workspace / open workspace?

Thank you.

**Comment by rxi** [comment]
You shouldn't have to create any files manually -- `.lite_workspace.lua` should be created in the project folder automatically when lite is closed, and reloaded when lite is opened back up.

I don't currently plan to support saving and loading separate workspaces, at the moment the plugin deals only with retaining a project's layout between closing and opening lite.
