### ISSUE TITLE
Issue: workspace-plugin doesn't work on windows 10

### ISSUE THREAD

**Issue by boruok** [rxi/lite-plugins#34]
**Lite version:** 
1.03
**OS:**
windows 10
**Issue description:**
workspace-plugin doesn't save and load .lite_workspace file outside C:\lite folder. Even if file precreated in root folder of project.
**Steps to reproduce:**
create new folder anywhere in system, make a new file with with preffered (go, lua, py...) extension, close lite.

**Comment by rxi** [comment]
I can't manage to reproduce this, the following works as expected on WIndows 10 64bit:
1. drag a project folder from desktop on to lite.exe
2. open some project files
3. close lite (`.lite_workspace.lua` is created in folder-from-desktop)
4. open lite (layout is restored)

**Comment by boruok** [comment]
Oh my bad, i thought that lite creates per-project workspace (treeview+layout). Would that possible in near future?

**Comment by rxi** [comment]
I'm a little confused, it *does* create a workspace per-project, the `.lite_workspace.lua` is made in the project's directory, loading a different project directory would load a different `.lite_workspace.lua` if it exists.

**Comment by boruok** [comment]
oh, now i see: lite reopens layout if you drag and drop folder into lite.exe **himself**. **NOT** while lite.exe is running. I have to be careful.
