### ISSUE TITLE
inanimate.lua making startup really slow

### ISSUE THREAD

**Issue by a327ex** [rxi/lite-plugins#43]
I really don't know what's happening but if inanimate is in my plugins folder it makes startup take up to 10 seconds. There's no log file that appears in case of an error or anything, and because it's such a small plugin I don't really know what could be happening. I've removed literally every other plugin except inanimate and the slowness persists.

**Comment by rxi** [comment]
This should be fixed now -- this issue also brought to light a problem with the core which should now also be fixed
