### ISSUE TITLE
Add support for shell files without .sh suffix

### ISSUE THREAD

**Issue by Anachron** [rxi/lite-plugins#45]
The [shell-language](https://github.com/rxi/lite-plugins/blob/master/plugins/language_sh.lua) plugin only works on files with the `.sh` suffix by default. At least on Linux a file doesn't need this suffix in order to be a valid shell file.

What I rather suggest is allowing to check the first line to be either `!/bin/sh` or `!/usr/bin/env sh` (or bash).

**Comment by rxi** [comment]
Note the change in this commit depends on functionality from the master/unreleased-1.08 version of `lite`
