### ISSUE TITLE
Feature request: If certain directory exist plugins would ignore them.

### ISSUE THREAD

**Issue by mcseptian** [rxi/lite-plugins#58]
It would be great if plugin only work on the working directory exclude dependencies (eg: node_modules, vendor, etc)

**Comment by rxi** [comment]
I'm not sure I fully understand, you might be looking for the `config.ignore_files` field:

```lua
config.ignore_files = { "^node_modules$", "^vendor$" }
```

This can be set from either your user module (for all projects) or your project module (for a specific project)

**Comment by mcseptian** [comment]
Yes, but it works globally. Therefore any plugin would refer to this setting rather than set its own config.

**Comment by mcseptian** [comment]
> I'm not sure I fully understand, you might be looking for the `config.ignore_files` field:
> 
> ```lua
> config.ignore_files = { "^node_modules$", "^vendor$" }
> ```
> 
> This can be set from either your user module (for all projects) or your project module (for a specific project)

Thanks for point this `config.ignore_files = "^%."` in core config. It works as expected.
